### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by Volcharka** [VKBots/VBot#31]
Бот иногда вылетает с ошибкой
```
←[35m17:47:01←[0m - ←[31mERROR←[0m - ←[39mПроизошла фатальная ошибка во время работы:
←[0m
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiohttp\client.py", line 220,
 in _request
    yield from resp.start(conn, read_until_eof)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiohttp\client_reqrep.py", li
ne 614, in start
    message = yield from httpstream.read()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiohttp\streams.py", line 625
, in read
    result = yield from super().read()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiohttp\streams.py", line 456
, in read
    yield from self._waiter
aiohttp.errors.ServerDisconnectedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "vbot.py", line 264, in <module>
    loop.run_until_complete(bot.run(loop))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 466, in run_u
ntil_complete
    return future.result()
  File "vbot.py", line 215, in run
    params=self.longpoll_values)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiohttp\client.py", line 582,
 in __await__
    resp = yield from self._coro
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiohttp\client.py", line 227,
 in _request
    raise aiohttp.ClientResponseError() from exc
aiohttp.errors.ClientResponseError
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x03DC6510>
```

**Comment by TiberiumN** [comment]
Хмм, у меня даже в новом боте такая проблема есть.
Запрос может сфейлиться.
Я сейчас в своём новом боте попробую сделать POST запрос для лонг пуллинг сервера вместо GET

**Comment by Noneeer** [comment]
+
