### ISSUE TITLE
Не запускается бот

### ISSUE THREAD

**Issue by Noneeer** [VKBots/VBot#37]
Все установил
```
Traceback (most recent call last):
  File "./vbot.py", line 14, in <module>
    from vkplus import VkPlus, Message
  File "C:\VBot-master\vkplus.py", line 8, in <module>
    import aiovk
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiovk\__init__.py", line 1, i
n <module>
    from aiovk.sessions import ImplicitSession, TokenSession, AuthorizationCodeSession
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiovk\sessions.py", line 5, i
n <module>
    from aiovk.drivers import HttpDriver
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiovk\drivers.py", line 98, i
n <module>
    class Socks5Driver(HttpDriver):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiovk\drivers.py", line 99, i
n Socks5Driver
    connector = SocksConnector
NameError: name 'SocksConnector' is not defined
```

**Comment by Myzon** [comment]
https://github.com/Fahreeve/aiovk/blob/master/aiovk/drivers.py#L99

Тут SocksConnector на ProxyConnector заменить в локальных файлах. И ещё в импорте заменить.

https://github.com/Fahreeve/aiovk/blob/master/aiovk/drivers.py#L8

Скоро, надеямся, пофиксят в aiovk эту ошибку.

**Comment by TiberiumN** [comment]
Инструкции @Myzon должны помочь
