### ISSUE TITLE
Ошибка при !тест

### ISSUE THREAD

**Issue by xakepmail** [VKBots/VBot#41]
Тест то работает, то не работает
2017-04-26T15:29:48.420936+00:00 app[worker.1]: [35m15:29:48[0m - [31mERROR[0m - [39mПроизошла ошибка при вызове команды '!тест' с аргументами []. Текст сообщения: '!тест'.Ошибка:
2017-04-26T15:29:48.420956+00:00 app[worker.1]: Traceback (most recent call last):
2017-04-26T15:29:48.420957+00:00 app[worker.1]:   File "/app/command.py", line 54, in process_command
2017-04-26T15:29:48.420958+00:00 app[worker.1]:     await self.system.call_command(cmd_text, msg_obj, cmd.args)
2017-04-26T15:29:48.420959+00:00 app[worker.1]:   File "/app/plugin_system.py", line 187, in call_command
2017-04-26T15:29:48.420959+00:00 app[worker.1]:     await command_function(*args, **kwargs)
2017-04-26T15:29:48.420960+00:00 app[worker.1]:   File "/app/plugins/example.py", line 35, in command
2017-04-26T15:29:48.420961+00:00 app[worker.1]:     attaches = "\n".join([str(attach) for attach in attachments])
2017-04-26T15:29:48.420962+00:00 app[worker.1]: TypeError: 'NoneType' object is not iterable
2017-04-26T15:29:48.420968+00:00 app[worker.1]: [0m

**Comment by TiberiumN** [comment]
Тут дело в том, что в тесте выводятся аттачи, прикреплённые к сообщению, а их нет. Сейчас пофикшу
