### ISSUE TITLE
Не запускается бот

### ISSUE THREAD

**Issue by Noneeer** [VKBots/VBot#56]
Ввел данные от аккаунта, раскомментировал строку, при запуске выдает ошибку

```
←[35m08:12:41←[0m - ←[33mWARNING←[0m - ←[39mАвторизация в ВКонтакте...←[0m
Creating a client session outside of coroutine
client_session: <aiohttp.client.ClientSession object at 0x03612D70>
Creating a client session outside of coroutine
client_session: <aiohttp.client.ClientSession object at 0x036A5E50>
←[35m08:12:41←[0m - ←[32mSUCCESS←[0m - ←[39mУспешная авторизация←[0m
←[35m08:12:41←[0m - ←[36mINFO←[0m - ←[39mЗагрузка плагинов...←[0m
←[35m08:12:41←[0m - ←[33mWARNING←[0m - ←[39mСчётчики←[0m
←[35m08:12:41←[0m - ←[33mWARNING←[0m - ←[39mПомощь←[0m
←[35m08:12:41←[0m - ←[33mWARNING←[0m - ←[39mДни рождения в группе←[0m
←[35m08:12:41←[0m - ←[33mWARNING←[0m - ←[39mКалькулятор←[0m
←[35m08:12:41←[0m - ←[33mWARNING←[0m - ←[39mВремя←[0m
←[35m08:12:41←[0m - ←[33mWARNING←[0m - ←[39mПример плагина←[0m
←[35m08:12:41←[0m - ←[33mWARNING←[0m - ←[39mКурсы валют←[0m
←[35m08:12:41←[0m - ←[33mWARNING←[0m - ←[39mПриветствие←[0m
←[35m08:12:41←[0m - ←[33mWARNING←[0m - ←[39mСписок плагинов←[0m
←[35m08:12:41←[0m - ←[33mWARNING←[0m - ←[39mСлучайные посты из пабликов←[0m
←[35m08:12:41←[0m - ←[31mERROR←[0m - ←[39mОшибка при загрузке плагина: memo.py←[0m
←[35m08:12:41←[0m - ←[33mWARNING←[0m - ←[39mЗеркало←[0m
←[35m08:12:41←[0m - ←[31mERROR←[0m - ←[39mОшибка при загрузке плагина: msg.py←[0m
←[35m08:12:41←[0m - ←[33mWARNING←[0m - ←[39mНовости←[0m
←[35m08:12:41←[0m - ←[33mWARNING←[0m - ←[39mРандом←[0m
←[35m08:12:41←[0m - ←[33mWARNING←[0m - ←[39mШутки←[0m
←[35m08:12:41←[0m - ←[33mWARNING←[0m - ←[39mВыключение←[0m
←[35m08:12:41←[0m - ←[33mWARNING←[0m - ←[39mСкриншот сайта←[0m
←[35m08:12:41←[0m - ←[33mWARNING←[0m - ←[39mШар предсказаний←[0m
←[35m08:12:41←[0m - ←[33mWARNING←[0m - ←[39mПеречеркиватель←[0m
←[35m08:12:41←[0m - ←[33mWARNING←[0m - ←[39mСообщение админу←[0m
←[35m08:12:41←[0m - ←[33mWARNING←[0m - ←[39mГолос←[0m
←[35m08:12:41←[0m - ←[33mWARNING←[0m - ←[39mПоиск видео←[0m
←[35m08:12:41←[0m - ←[33mWARNING←[0m - ←[39mПогода←[0m
←[35m08:12:41←[0m - ←[33mWARNING←[0m - ←[39mВы используете общественный ключ для openweathermap.org! Рекомендуем вам пол
учить личный!←[0m
←[35m08:12:41←[0m - ←[32mSUCCESS←[0m - ←[39mЗагрузка плагинов завершена←[0m
←[35m08:12:41←[0m - ←[32mSUCCESS←[0m - ←[39mПриступаю к приему сообщений←[0m
←[35m08:12:45←[0m - ←[33mWARNING←[0m - ←[39mВведите данные для сервиса решения капч в settings.py!←[0m
Task exception was never retrieved
future: <Task finished coro=<VkPlus.handle_queues() done, defined at C:\Users\Administrator\Desktop\test\VBot-master\vkp
lus.py:101> exception=ClientConnectorError(11001, 'Cannot connect to host m.vk.comhttps:443 ssl:True [getaddrinfo failed
]')>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiohttp\connector.py", line 3
75, in connect
    proto = yield from self._create_connection(req)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiohttp\connector.py", line 6
32, in _create_connection
    _, proto = yield from self._create_direct_connection(req)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiohttp\connector.py", line 6
43, in _create_direct_connection
    hosts = yield from self._resolve_host(req.url.raw_host, req.port)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiohttp\connector.py", line 6
15, in _resolve_host
    self._resolver.resolve(host, port, family=self._family)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiohttp\resolver.py", line 30
, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\concurrent\futures\thread.py", line 55, in
run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\test\VBot-master\vkplus.py", line 104, in handle_queues
    if await self.process_queue(self.queues[i], i):
  File "C:\Users\Administrator\Desktop\test\VBot-master\vkplus.py", line 132, in process_queue
    result = await self.execute(execute, SendFrom(queue_id))
  File "C:\Users\Administrator\Desktop\test\VBot-master\vkplus.py", line 206, in execute
    return unquote(await api_method("execute", code=quote(code)))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiovk-1.1.0-py3.6.egg\aiovk\a
pi.py", line 9, in __call__
    return await getattr(self, method_name)(**method_kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiovk-1.1.0-py3.6.egg\aiovk\a
pi.py", line 25, in __call__
    return await self._api._session.make_request(self, timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiovk-1.1.0-py3.6.egg\aiovk\s
essions.py", line 25, in make_request
    return await self.send_api_request(method_request._method_name, params, timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiovk-1.1.0-py3.6.egg\aiovk\s
essions.py", line 46, in send_api_request
    await self.authorize()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiovk-1.1.0-py3.6.egg\aiovk\s
essions.py", line 86, in authorize
    url, html = await self.process_auth_form(html)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiovk-1.1.0-py3.6.egg\aiovk\s
essions.py", line 128, in process_auth_form
    url, html = await self.driver.post_text(form_url, form_data)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiovk-1.1.0-py3.6.egg\aiovk\u
tils.py", line 28, in wrapper
    return await func(self, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiovk-1.1.0-py3.6.egg\aiovk\m
ixins.py", line 26, in post_text
    return await super().post_text(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiovk-1.1.0-py3.6.egg\aiovk\d
rivers.py", line 91, in post_text
    response = await self.session.post(url, data=data)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiohttp\client.py", line 621,
 in __await__
    resp = yield from self._coro
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiohttp\client.py", line 225,
 in _request
    conn = yield from self._connector.connect(req)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiohttp\connector.py", line 3
80, in connect
    .format(key, exc.strerror)) from exc
aiohttp.client_exceptions.ClientConnectorError: [Errno 11001] Cannot connect to host m.vk.comhttps:443 ssl:True [getaddr info failed]

```

**Comment by TiberiumN** [comment]
Интернета нет

**Comment by TiberiumN** [comment]
@Myzon неправильное форматирование адреса?

**Comment by Noneeer** [comment]
@TiberiumN Интернет есть как-бы, старая версия бота нормально запускалась

**Comment by Myzon** [comment]
@TiberiumN не должно быть такого. Капчу потребовал вк, после этого ушёл непонятный запрос. Надо тестить.
@Noneeer возможно, ты запятую забыл в кортеже USERS?

**Comment by TiberiumN** [comment]
@Myzon тут же gethostaddr, значит это ошибка неправильного хоста.
Он какой-то странный - "m.vk.comhttps"

**Comment by Myzon** [comment]
@TiberiumN яяну так и понял. Ну, я нигде не взаимодействую с такими вещами. Я тестил - работало

**Comment by Noneeer** [comment]
@TiberiumN Нет, запятая между логином и паролем есть

**Comment by Myzon** [comment]
@Noneeer  После логина с паролем

**Comment by Noneeer** [comment]
@Myzon Ее там не было, поставил, все заработало)
