### ISSUE TITLE
Ошибка работы с базой данных mysql

### ISSUE THREAD

**Issue by Noneeer** [VKBots/VBot#59]
upd: к базе коннектится, создает там 2 таблицы и выдает ошибку
```
Traceback (most recent call last):
  File "vbot.py", line 16, in <module>
    from database import *
  File "C:\Users\Administrator\Desktop\test\VBot-master\database.py", line 63, in <module>
    User.create_table(True)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\peewee.py", line 4966, in cre
ate_table
    if fail_silently and cls.table_exists():
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\peewee.py", line 4962, in tab
le_exists
    return cls._meta.db_table in cls._meta.database.get_tables(**kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\peewee.py", line 4259, in get
_tables
    return [row for row, in self.execute_sql('SHOW TABLES')]
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\peewee_async.py", line 1024,
in execute_sql
    return super().execute_sql(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\peewee.py", line 3766, in exe
cute_sql
    cursor = self.get_cursor()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\peewee.py", line 3714, in get
_cursor
    return self.get_conn().cursor()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\peewee.py", line 3703, in get
_conn
    self.connect()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\peewee.py", line 3680, in con
nect
    self._local.conn = self._create_connection()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\peewee.py", line 3708, in _cr
eate_connection
    return self._connect(self.database, **self.connect_kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\peewee.py", line 4256, in _co
nnect
    return mysql.connect(db=database, **conn_kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pymysql\__init__.py", line 90
, in Connect
    return Connection(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pymysql\connections.py", line
 706, in __init__
    self.connect()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pymysql\connections.py", line
 922, in connect
    self.host_info = "socket %s:%d" % (self.host, self.port)
TypeError: %d format: a number is required, not str
```

**Comment by TiberiumN** [comment]
Это не выглядит проблемой бота
