### ISSUE TITLE
ошибка при выполнении некоторых модулей

### ISSUE THREAD

**Issue by cash-metall** [VKBots/VBot#65]
"скажи" и  "видео" не работают 
`←[35m23:03:45←[0m - ←[36mINFO←[0m - ←[39mКоманда 'скажи' из конференции 1 с аргументами ['приве']←[0
m
←[35m23:03:47←[0m - ←[31mERROR←[0m - ←[39mНекому выполнять: docs.getUploadServer←[0m
←[35m23:03:47←[0m - ←[31mERROR←[0m - ←[39mПроизошла ошибка при вызове команды 'скажи' с аргументами
['приве']. Текст сообщения: '!скажи приве'.Ошибка:
Traceback (most recent call last):
  File "d:\git\VBot\command.py", line 32, in process_command
    return await self.system.call_command(cmd_text, msg_obj, cmd.args)
  File "d:\git\VBot\plugin_system.py", line 176, in call_command
    await command_function(*args, **kwargs)
  File "d:\git\VBot\plugins\tts.py", line 43, in say_text_google
    await upload_voice(msg, audio_file)
  File "d:\git\VBot\plugins\tts.py", line 93, in upload_voice
    url = upload_server.get('upload_url')
AttributeError: 'NoneType' object has no attribute 'get'
←[0m
←[35m23:03:53←[0m - ←[36mINFO←[0m - ←[39mКоманда 'скажи' из конференции 1 с аргументами ['hello']←[0
m
←[35m23:03:54←[0m - ←[31mERROR←[0m - ←[39mНекому выполнять: docs.getUploadServer←[0m
←[35m23:03:55←[0m - ←[31mERROR←[0m - ←[39mПроизошла ошибка при вызове команды 'скажи' с аргументами
['hello']. Текст сообщения: '!скажи hello'.Ошибка:
Traceback (most recent call last):
  File "d:\git\VBot\command.py", line 32, in process_command
    return await self.system.call_command(cmd_text, msg_obj, cmd.args)
  File "d:\git\VBot\plugin_system.py", line 176, in call_command
    await command_function(*args, **kwargs)
  File "d:\git\VBot\plugins\tts.py", line 43, in say_text_google
    await upload_voice(msg, audio_file)
  File "d:\git\VBot\plugins\tts.py", line 93, in upload_voice
    url = upload_server.get('upload_url')
AttributeError: 'NoneType' object has no attribute 'get'
`←[0m

`←[35m23:07:47←[0m - ←[36mINFO←[0m - ←[39mКоманда 'видео' из конференции 1 с аргументами ['приятного'
, 'просмотра']←[0m
←[35m23:07:47←[0m - ←[31mERROR←[0m - ←[39mНекому выполнять: video.search←[0m
←[35m23:07:48←[0m - ←[31mERROR←[0m - ←[39mПроизошла ошибка при вызове команды 'видео' с аргументами
['приятного', 'просмотра']. Текст сообщения: '!видео приятного просмотра'.Ошибка:
Traceback (most recent call last):
  File "d:\git\VBot\command.py", line 32, in process_command
    return await self.system.call_command(cmd_text, msg_obj, cmd.args)
  File "d:\git\VBot\plugin_system.py", line 176, in call_command
    await command_function(*args, **kwargs)
  File "d:\git\VBot\plugins\videos.py", line 21, in video_search
    vids = resp.get('items')
AttributeError: 'NoneType' object has no attribute 'get'
←[0m`

**Comment by cash-metall** [comment]
двач и мемы та же ошибка 
`←[35m23:17:16←[0m - ←[36mINFO←[0m - ←[39mКоманда 'мемы' из конференции 1 с аргументами []←[0m
←[35m23:17:16←[0m - ←[31mERROR←[0m - ←[39mНекому выполнять: wall.get←[0m
←[35m23:17:16←[0m - ←[31mERROR←[0m - ←[39mПроизошла ошибка при вызове команды 'мемы' с аргументами [
]. Текст сообщения: '!мемы'.Ошибка:
Traceback (most recent call last):
  File "d:\git\VBot\command.py", line 32, in process_command
    return await self.system.call_command(cmd_text, msg_obj, cmd.args)
  File "d:\git\VBot\plugin_system.py", line 176, in call_command
    await command_function(*args, **kwargs)
  File "d:\git\VBot\plugins\memes.py", line 64, in just_memes
    await give_memes(msg, group_id)
  File "d:\git\VBot\plugins\memes.py", line 34, in give_memes
    items = random.sample(data.get('items'), len(data.get('items')))
AttributeError: 'NoneType' object has no attribute 'get'
←[0m
←[35m23:17:19←[0m - ←[36mINFO←[0m - ←[39mКоманда 'двач' из конференции 1 с аргументами []←[0m
←[35m23:17:19←[0m - ←[31mERROR←[0m - ←[39mНекому выполнять: wall.get←[0m
←[35m23:17:19←[0m - ←[31mERROR←[0m - ←[39mПроизошла ошибка при вызове команды 'двач' с аргументами [
]. Текст сообщения: '!двач'.Ошибка:
Traceback (most recent call last):
  File "d:\git\VBot\command.py", line 32, in process_command
    return await self.system.call_command(cmd_text, msg_obj, cmd.args)
  File "d:\git\VBot\plugin_system.py", line 176, in call_command
    await command_function(*args, **kwargs)
  File "d:\git\VBot\plugins\memes.py", line 58, in twoch_memes
    await give_memes(msg, group_id)
  File "d:\git\VBot\plugins\memes.py", line 34, in give_memes
    items = random.sample(data.get('items'), len(data.get('items')))
AttributeError: 'NoneType' object has no attribute 'get'
←[0m
`

**Comment by Myzon** [comment]
Для работы этих плагинов необходим аккаунт пользователя.
Можно ввести дополнительно к токену(в настройках есть пример).
Если это не решение - отпишитесь с более подробным описание проблемы(какие данные есть, где пишите и т.д.)
